export const ALL_COURSE_REQUEST = "ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = "ALL_COURSE_FAIL";

export const ALL_COURSE_WITHOUT_FILTER_REQUEST = "ALL_COURSE_WITHOUT_FILTER_REQUEST";
export const ALL_COURSE_WITHOUT_FILTER_SUCCESS = "ALL_COURSE_WITHOUT_FILTER_SUCCESS";
export const ALL_COURSE_WITHOUT_FILTER_FAIL = "ALL_COURSE_WITHOUT_FILTER_FAIL";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_RESET = "ENROLL_COURSE_RESET";
export const ENROLL_COURSE_FAIL = "ENROLL_COURSE_FAIL";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_RESET = "UPDATE_COURSE_RESET";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";

export const CREATE_MODULE_REQUEST = "CREATE_MODULE_REQUEST";
export const CREATE_MODULE_SUCCESS = "CREATE_MODULE_SUCCESS";
export const CREATE_MODULE_RESET = "CREATE_MODULE_RESET";
export const CREATE_MODULE_FAIL = "CREATE_MODULE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";