export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST";
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS";
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL";

export const MY_COURSES_REQUEST = "MY_COURSES_REQUEST";
export const MY_COURSES_SUCCESS = "MY_COURSES_SUCCESS";
export const MY_COURSES_FAIL = "MY_COURSES_FAIL";

export const ALL_COURSES_REQUEST = "ALL_COURSES_REQUEST";
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAIL = "ALL_COURSES_FAIL";

export const DELETE_COURSES_REQUEST = "DELETE_COURSES_REQUEST";
export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const DELETE_COURSES_RESET = "DELETE_COURSES_RESET";
export const DELETE_COURSES_FAIL = "DELETE_COURSES_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
